---
- name: restart_chrony
  service:
     name: chronyd
     state: restarted 

- name: restart_firewalld
  service:
     name: firewalld
     state: restarted 

- name: restart_plex
  service:
     name: plexmediaserver
     state: restarted
