---
- name: Preparing and intalling Plex Media Server on host
  hosts: plex_hosts
  become: True
  roles:
    - role: host-setup-common
    - role: rhel-plex-server-config
  vars:
    base_hostname: plex
    domain: acanorex.io
    time_servers:
      - clock.nyc.he.net
      - clock.fmt.he.net
    time_zone: America/Chicago
    local_user_list:
      - user_name: arlaporte
        uid: 1001
    rhsm_repositories_enabled:
      - baseos
      - appstream
      - extras-common
    rhel_pkgs_to_install:
      - NetworkManager
      - bind-utils
      - yum-utils
      - tmux
      - vim-enhanced
      - openssh-clients
      - openssh-server
      - chrony
      - curl
      - wget
      - tcpdump
      - iproute
      - firewalld
      - sysstat
      - ethtool
      - nfs-utils
      - epel-release
      - bind-utils
      - ipa-client
    rhel_pkgs_to_remove:
      - postfix
      - ntpd
      - cloud-init
    enabled_system_services:
      - chronyd
      - sshd
      - firewalld
    disabled_system_services: []
  vars_files:
    - vars/vaulted/plex-vaulted-vars.yml
