---
# This play runs on the remote host to build the virtual machine
# using virt-* commands
- name: Starting playbook to deploy a CentOS Stream 9 base Plex server
  hosts: kvm01.acanorex.io
  tasks:
    - name: 'Importing the roles needed for this play...'
      ansible.builtin.import_role:
        name: kvm-vm-provisioning
  vars_files:
    - vars/libvirt-plex.yml
    - vars/vaulted/libvirt-plex-vaulted.yml
  tags:
    - create_vm
    - delete_vm
    - start_vm

