---
# This play runs on the remote host to build the virtual machine
# using virt-* commands
- name: Starting playbook to deploy a Rocky Linux 9 virtual machine to use with Kolla Ansible.
  hosts: kvm1.voltron.xyz
  vars_files:
    - vars/libvirt-rocky-9.yml
    - vars/vaulted/libvirt-rocky-9.yml
  roles:
    - kvm-vm-provisioning
  tags:
    - create_vm
    - delete_vm
    - start_vm
