---
# This play runs on the remote host to build the virtual machine
# using virt-* commands
- name: Starting playbook to deploy a Red Hat OpenStack Platform 16 Director virtual machine
  hosts: kvm1.voltron.xyz
  vars_files:
    - vars/libvirt-osp16.yml
    - vars/vaulted/libvirt-osp16.yml
  tasks:
  roles:
    - kvm-vm-provisioning
  tags:
    - create_vm
    - delete_vm
    - start_vm