---
# This playbook runs on the kvm host to build the virtual machine
# that will be used as an openstack controller
# note: The virtual machine while it does get an OS image intalled
#       as part of this process, it is for the most part irrelevant
#       as the OS will be wiped and reinstalled during the openstack
#       installation through director/tripleo
- hosts: kvm_host
  become: True
  tasks:
    - name:  Building an KVM based OpenStack Controller Virtual Machine
      import_role: 
        name: kvm-vm-provisioning
  vars_files:
    - vars/libvirt.yaml

