---
# defaults file 
# Go over variables below and pass them in extra vars, playbook vars,
# vars_files, inventory file or whatever which overwrite these values!

# General Settings
# 
vm_boot_on_create: false
vm_base_name: osp-ctrl01
vm_fqdn_name: osp-ctrl01.lab.acanorex.io

# these variable has been vaulted
# vm_root_pw:
# vm_root_pub_key: 
#
vm_os_variant: rhel9.2
vm_os_family: redhat

# Virtual machine resources
vm_vcpu_count: 8
vm_ram_size_mb: 16384
vm_root_disk_gb: 250

# Linux bridges to attach io
# br-provisioning: provisioning bridge ( does not get an ip  )
# br-mgmt: external management bridge. This is the trunk interface for 
#          external / routable networks
# br-lab-int: internal bridge. This is the trunk interface for 
#          non-routable or internal tagged networks on the controller
# br-storage_mgmt:  storage network (10GB + 9k mtu)
# these are looped using jinja2 
# templating
vm_net_bridges:
  - br-provisioning
  - br-mgmt
  - br-lab_int
  - br-storage_mgmt

# vm default network interface settings
# additional ip addresses are configured below
vm_if_configure_ip: false
vm_if_dev: eth1
vm_if_addr: 172.25.48.200
vm_if_cidr: 23
vm_if_gateway: 172.25.48.1
vm_if_dns1: 172.25.49.253
vm_if_dns2: 172.31.103.254

# extra interfaces to configure 
# these do not get a gateway
vm_enable_extra_nics: false
vm_extra_if_dev:
  - ifname: eth1
    ip: 172.30.1.187
    netmask: 255.255.255.192
    ifmtu: 9000
  - ifname: eth2
    ip: 172.30.9.251
    netmask: 255.255.254.0 
    ifmtu: 1500

# vm virtual disks 
vm_base_src_image: rhel-9.2-x86_64-kvm.qcow2
vm_base_src_disk_path: /lv_data/kvm_base_images
vm_dest_disk_path: /lv_data/kvm_images
vm_dest_disk_file: '{{ vm_base_name }}_root_disk.qcow2'
# rhel8 qcow2 images the root disk partition is sda3
# rhel9 qcow2 images the root disk partition is sda4
vm_root_disk_partition: /dev/sda4

# vm extra disks setting
vm_enable_extra_disk: false
vm_extra_disk_size_gb: 1024
vm_dest_extra_disk_file: '{{ vm_base_name  }}_pulp_disk.qcow2'
vm_extra_disk_physname: /dev/vdb
vm_extra_disk_vg_name: vg_pulp
vm_extra_disk_lv_name: lv_pulp
vm_extra_disk_mount_point: /var/lib/pulp

# vm rhel portal subscription manager settings
# used for the temporary installation of packages
# during vm build some of these parameters are 
# vaulted some are plain text
vm_portal_registration_enable: false
#vm_portal_user: 
#vm_portal_pw: 
#vm_portal_pool: 
