---
# This play runs on the remote host to build the virtual machine
# using virt-* commands
- name: Starting playbook to deploy a CentOS 8 Streams base virtual machine
  hosts: kvm1.voltron.xyz
  roles:
    - kvm-vm-provisioning
  vars_files:
    - vars/libvirt-centos-8-vm.yml
    - vars/vaulted/libvirt-centos-8-vm.yml
  tags:
    - create_vm
    - delete_vm
    - start_vm