---
# This play runs on the remote host to build the virtual machine
# using virt-* commands
- hosts: kvm_host
  become: True
  tasks:
    - name:  Importing kvm-vm-provisioning role for deployment of virtual machine
      import_role: 
        name: kvm-vm-provisioning
  vars_files:
    - vars/libvirt-rhel-vm-snort.yaml

