---
- name: Update apt cache on Debian based hosts
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'
  tags:
    - update_apt_cache

- name: Remove packages defined in vars
  ansible.builtin.apt:
    name: '{{ debian_pkgs_to_remove }}'
    state: absent
  when: ansible_os_family == 'Debian'
  tags:
    - remove_pkgs

- name: Install packages defined in vars
  ansible.builtin.apt:
    name: '{{ debian_pkgs_to_install }}'
    state: latest
  when: ansible_os_family == 'Debian'
  tags:
    - install_pkgs
