---
- name: 'Configure chronyd from template'
  ansible.builtin.template:
    src: templates/chrony_server.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0440
  when: 
    - ansible_os_family == 'RedHat'
  tags: 
    - base_services
  notify: 
     - restart_chrony 
 
- name: 'Ensure base services are enabled and started'
  ansible.builtin.service:
    name: '{{ item }}'
    state: started
    enabled: yes
  loop: '{{ base_services }}'
  when: 
    - ansible_os_family == 'RedHat'
  tags: 
    - base_services
 