---
- name: 'Render bifrost group var files to the bifrost group_vars directory'
  ansible.builtin.template:
    src: bf_group_vars.j2
    dest: '{{ item }}'
    owner: '{{ bf_install_user | default("bifrost") }}'
    group: '{{ bf_install_user | default("bifrost") }}'
    mode: 0644
  register: template_render
  loop:
    - '{{ bf_install_path }}/playbooks/inventory/group_vars/target'
    - '{{ bf_install_path }}/playbooks/inventory/group_vars/localhost'
  tags:
    - configure_bifrost

- name: 'Run the Bitfrost environment configuration script'
  ansible.builtin.shell: |
    ./scripts/env-setup.sh
  args:
    executable: /usr/bin/bash
    chdir: '{{ bf_install_path }}'
  register: bf_setenv
  become: yes
  become_user: '{{ bf_install_user | default("bifrost") }}'
  become_method: su 
  become_flags: '--login'
  tags:
    - configure_bifrost

- name: 'Display playbook success message'
  ansible.builtin.debug:
    msg: 
      - 'Bifrost is now configured and ready to be deployed on the remote host'
      - 'To deploy Bifrost run the playbook on the remote host:'
      - 'source /opt/stack/bifrost/bin/activate'
      - 'cd {{ bf_install_path }}'
      - 'ansible-playbook -i playbooks/inventory/target playbooks/install.yaml -e ipv4_gateway={{ bf_dnsmasq_router }}'
      - 'This playbook has completed its purpose, the rest of the lifecycle is managed on the Biforst remote host.'
      - 'Bifrost documentation: https://docs.openstack.org/bifrost/latest/'
  when: 
    - bf_setenv.rc == 0
  tags:
    - configure_bifrost
