---
- name: 'Create the git temporary directory with proper permissions'
  ansible.builtin.file:
    path: '/home/{{ bf_install_user }}/.ansible/tmp'
    mode: 0755
    owner: '{{ bf_install_user | default("bifrost") }}'
    group: '{{ bf_install_user | default("bifrost") }}'
    state: directory
  become: yes
  become_user: '{{ bf_install_user | default("bifrost") }}'
  become_method: su 
  become_flags: '--login'
  tags:
    - install_bifrost

- name: 'Clone the bifrost repo' 
  ansible.builtin.git:
    repo: '{{ bf_repo }}'
    version: '{{ bf_repo_branch }}'
    dest: '{{ bf_install_path }}'
    clone: true
    force: false
  become: yes
  become_user: '{{ bf_install_user | default("bifrost") }}'
  become_method: su 
  become_flags: '--login'
  tags:
    - install_bifrost
