---
- name: 'Extracting overcloud deployment images into the {{ uc_home_path }}/overcloud_images directory'
  unarchive: 
    remote_src: yes
    src: '{{ item }}'
    dest: '{{ undercloud_home_path }}/rhosp_overcloud_deployment_images'
  loop:
    - /usr/share/rhosp-director-images/overcloud-full-latest-16.2.tar 
    - /usr/share/rhosp-director-images/ironic-python-agent-latest-16.2.tar
  tags:
    - undercloud_post_install

- name: 'Verify Glance API is operational before uploading deployment images to undercloud'
  shell: |
    source '{{ undercloud_home_path }}'/stackrc; openstack image list > /dev/null
  args:
    executable: /bin/bash
  changed_when: false
  register: check_endpoint
  tags:
    - undercloud_post_install
 
- name: 'Uploading deployment images to undercloud Glance instance'
  shell: |
    source '{{ undercloud_home_path }}'/stackrc;
    openstack overcloud image upload --image-path '{{ undercloud_home_path }}'/rhosp_overcloud_deployment_images > /dev/null
  args:
    executable: /bin/bash
  when: check_endpoint.rc == 0
  tags:
    - undercloud_post_install