---
- name: restart_unbound
  service:
    name: unbound
    state: restarted

- name: restart_sshd
  service:
    name: sshd
    state: restarted

- name: restart_ufw
  service:
    name: ufw
    state: restarted

